-- Create Feed table
CREATE TABLE "Feed" (
  id SERIAL PRIMARY KEY,
  url TEXT NOT NULL UNIQUE,
  lastFetched TIMESTAMP,
  etag TEXT,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create FeedItem table
CREATE TABLE "FeedItem" (
  id SERIAL PRIMARY KEY,
  feedId INTEGER NOT NULL REFERENCES "Feed"(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  pubDate TIMESTAMP NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_feeditem_pubdate ON "FeedItem"(pubDate);

-- Create Subscriber table
CREATE TABLE "Subscriber" (
  id SERIAL PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  discordWebhook TEXT,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create Preference table
CREATE TABLE "Preference" (
  id SERIAL PRIMARY KEY,
  subscriberId INTEGER NOT NULL REFERENCES "Subscriber"(id) ON DELETE CASCADE,
  vapidPublicKey TEXT NOT NULL,
  vapidPrivateKey TEXT NOT NULL,
  pushToken TEXT,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
