-- Migration: Initial schema
-- This file is autogenerated by Prisma

CREATE TABLE "Feed" (
  "id" SERIAL PRIMARY KEY,
  "rssUrl" TEXT NOT NULL UNIQUE,
  "lastFetch" TIMESTAMPTZ,
  "etag" TEXT
);

CREATE TABLE "Article" (
  "id" SERIAL PRIMARY KEY,
  "feedId" INTEGER NOT NULL REFERENCES "Feed"("id"),
  "title" TEXT NOT NULL,
  "body" TEXT NOT NULL,
  "template" TEXT,
  "pubDate" TIMESTAMPTZ NOT NULL
);

CREATE INDEX "idx_article_pub_date" ON "Article" ("pubDate");

CREATE TABLE "Subscriber" (
  "id" SERIAL PRIMARY KEY,
  "email" TEXT NOT NULL UNIQUE,
  "webhook" TEXT,
  "vapidPublicKey" TEXT,
  "vapidPrivateKey" TEXT
);

CREATE TABLE "Preference" (
  "id" SERIAL PRIMARY KEY,
  "subscriberId" INTEGER NOT NULL REFERENCES "Subscriber"("id"),
  "topic" TEXT NOT NULL,
  "enabled" BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE "PushToken" (
  "id" SERIAL PRIMARY KEY,
  "subscriberId" INTEGER NOT NULL REFERENCES "Subscriber"("id"),
  "token" TEXT NOT NULL
);

-- Add indexes as needed
